title: Status Bar  # Empty
app:
  id: status.bar    # Status bar
  text_multithreading: true   # false
  antialiasing: true    # false
  try_opengles_first: true    # false
assets: 
  default: /Users/akshayraina/Mecha/mecha-launcher/status_bar
window:
  size: [480, 37]  # [1024, 768]
  position: [0, 0]  # [0, 0]
  min_size: [480, 40]  # None
  max_size: null    # None
  visible: true   # true
  resizable: true   # true
  decorations: true   # true
  transparent: true    # false
  always_on_top: false    # false
  icon_path: null # Todo
layout:
  left: ["clock"]
  center: ["window_title"]
  right: ["wifi", "bluetooth", "battery",]
modules:
  clock:
    format: "%I:%M %p" # https://docs.rs/chrono/latest/chrono/format/strftime/index.html
  bluetooth:
    icon:
      on: /pngs/bluetooth_on.png
      off: /pngs/bluetooth_off.png
      connected: /pngs/bluetooth_connected.png
  wifi:
    icon:
      off: /pngs/wifi_off.png
      on: /pngs/wifi_on.png
      low: /pngs/wifi_low.png
      weak: /pngs/wifi_weak.png
      good: /pngs/wifi_good.png
      strong: /pngs/wifi_strong.png
  battery:
    icon:
      level_100: /pngs/battery_100.png
      level_90: /pngs/battery_90.png
      level_80: /pngs/battery_80.png
      level_70: /pngs/battery_70.png
      level_60: /pngs/battery_60.png
      level_50: /pngs/battery_50.png
      level_40: /pngs/battery_40.png
      level_30: /pngs/battery_30.png
      level_20: /pngs/battery_20.png
      level_10: /pngs/battery_10.png
      level_0: /pngs/battery_0.png
